/* cppad/config.h.  Generated by configure.  */
/* cppad/config.h.in.  Generated from configure.ac by autoheader.  */

/* is CppADvector == boost::numeric::ublas::vector */
#define CppAD_BOOSTVECTOR 0

/* is CppADvector == CppAD::vector */
#define CppAD_CPPADVECTOR 1

/* is CppADvector == std::vector */
#define CppAD_STDVECTOR 0

/* Name of package */
#define PACKAGE "cppad"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "cppad@list.coin-or.org"

/* Define to the full name of this package. */
#define PACKAGE_NAME "CppAD"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "CppAD 20061223"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "cppad"

/* Define to the version of this package. */
#define PACKAGE_VERSION "20061223"

/* Version number of package */
#define VERSION "20061223"

/* Define to `__inline__' or `__inline' if that's what the C compiler
   calls it, or to nothing if 'inline' is not supported under any name.  */
#ifndef __cplusplus
/* #undef inline */
#endif
